spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://112.125.27.159:3307/db_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 连接池配置信息
#    druid:
#      initial-size: 5 #初始化提供的连接数
#      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      min-idle: 5 # 数据库连接池的最小维持连接数
#      max-wait: 60000 # 配置获取连接等待超时的时间
#      max-active: 20 # 最大活动数
#      filter:
#        stat:
#          log-slow-sql: true # 打印慢SQL记录
#          slow-sql-millis: 5000 # 慢SQL记录
#      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒

  # 配置jpa
  jpa:
    show-sql: true # jpa打印sql语句
    hibernate:
      ddl-auto: update
  # 配置redis
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0
    password:
    # springboot 2.0 redis默认客户端已换成lettuce
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

# 配置日志
logging:
  level: # 日志级别
    root: info
    com.aitao.myblog: debug
  file:
    path: log/blog-dev.log # 日志文件存放路径
